serf/merge_delegate.go
Helps pass errors from a merge cancel through to memberlist. Depends on hashicorp/memberlist#28
=> Custom error for merge delegate

serf/config.go, serf/serf.go
This can't be merged until hashicorp/memberlist#37 has been merged. It ups the corresponding serf version which maps to the new memberlist version.
=> Bumps protocol version to 5 to get memberlist version 3.

command/agent/command.go, website/source/docs/agent/options.html.markdown
* Reword explanation for `-discover`
* Add default port to -bind (matches -rpc-addr)
=> Updates docs

serf/config.go, serf/serf.go
Over on https://github.com/hashicorp/memberlist/pull/50 we made memberlist smarter about interoperating with v2/v3 so we don't need to bump the Serf protocol; this should ease rolling out newer versions of Serf and Consul.
=> Bumps protocol version back down as we've made memberlist smarter.

command/agent/agent.go
This is a much smaller PR than https://github.com/hashicorp/serf/pull/311 that achieves what I wanted to get from https://github.com/hashicorp/serf/issues/306 but by adding event_handlers as a field to the output of info, as suggested by @ryanuber.
I actually like this solution a lot better, and probably would have done this to start with if I had realized that info already had a bunch similar data in it.
There may still be some merit to the getconfig command, but I think for the most part it's a better approach to just add additional fields to info. This was the only data I really wanted to pull, so it's all I'm adding for now.
The cod should be fairly self-explanatory, it just loops over the EventHandlers, and splits it into key/value pairs by cutting it at the first "=" sign. This is …
=> Show event handlers in info output

command/agent/command.go, website/source/docs/agent/options.html.markdown
=> Add example for specifying an IPv6 address.

serf/serf.go, serf/serf_test.go
This was causing sporadic test failures in Consul and Nomad. It should also make peer removal more timely instead of waiting for the reconcile period.
/cc: @slackpad @dadgar
=> serf: on force-leave, send MemberLeave message to EventCh

website/Gemfile.lock, website/Makefile, website/README.md, website/config.rb, website/source/layouts/layout.erb
This PR adds an 'Edit this page' link everywhere on the [Serf website](https://serfdom.io/) except the homepage. Note that — owing to some deployment issues on a different site — I closed my [last PR to this effect](https://github.com/hashicorp/serf/pull/320) and opened this one. 
As in the other PR, I have added a `Makefile` to the `website` directory and updated the README accordingly. I have also updated the `Gemfile.lock` file to point to the latest `middleman-hashicorp` gem.
=> Add "Edit this page" link everywhere except /

Makefile
* Adds the suffix to the subnet script call.
* Gets rid of unused integ test target.
* Runs the tests in serial, otherwise we get port conflicts.
/cc @sethvargo
=> Fixes up some things in the Makefile.

serf/serf.go, serf/serf_test.go
Fixes an incidental bug that I found while investigating https://github.com/hashicorp/consul/issues/1346. This will fix that issue, but for the wrong reason. We should merge this, especially for the note about how this isn't a complete fix in case we depend on this in the future. I'll make the real fix for the issue above over in Consul.
=> Captures the protocol versions for a node when an update event fires.

command/agent/ipc.go
I believe this is a relict of the past. Error variable doesn't mutate here since last `err != nil` check.
=> Remove unreachable error check

scripts/setup_test_subnet.sh
Avoid calling sudo 253 times if the first one gets Ctrl-C'd.
Tell the user that sudo is prompting, and why.
Move the OS sanity check to the front, pre ping.
https://github.com/hashicorp/serf/issues/343
=> modify sudo and ordering, use set -e fail early

command/agent/util_test.go
It looks like the new Travis platform doesn't support IPv6 (https://blog.travis-ci.com/2015-11-27-moving-to-a-more-elastic-future) so explicitly choosing an IPv4 address to fix build failures. Here's an example build failure that looks IPv6-related - https://travis-ci.org/hashicorp/serf/builds/97754919.
=> Forces unit tests to bind to IPv4 address.

website/scripts/deploy.sh
Should fix occassional issues with application/octet-stream mime type
assets breaking things on the site.
=> website: Fix mime types for some assets on deploy

serf/config.go, serf/delegate_test.go, serf/serf.go, serf/serf_internals_test.go, serf/serf_test.go
This fixes https://github.com/hashicorp/consul/issues/1062 by storing the intents per-node. This will buffer all intents for a 5 minute period and intents are now stored in a map indexed per-node (later intents of each type by Lamport time will overwrite old ones). This should provide a reasonable footprint of memory usage without throwing out recent intents, which is what leads to the infinite rebroadcasts.
=> Fixes intent queue overflow by storing intents per-node.

.travis.yml, GNUmakefile
This prevents travis from testing Serf twice, once during `make` and a second time during `make test`.  Found while looking at:
https://travis-ci.org/hashicorp/serf/builds/150837335
=> Use `make bin` instead of `make` for the travis install command

scripts/build.sh
This commit adds `solaris` to the list of cross-compiled operating systems such that binaries capable of running on Illumos will be produced by `make bin`.
No other changes are necessary to allow building.
=> build: Add target for Illumos

cmd/serf/command/agent/command.go, cmd/serf/command/agent/config.go, cmd/serf/command/agent/config_test.go, website/source/docs/agent/options.html.markdown
(Per discussion in https://groups.google.com/forum/#!topic/serfdom/SgKQQ9LkDw0)
Exposes the broadcast timeout config param, which needs to be tuned for cases when tons of nodes join at the same time and the default 5 seconds is insufficient.
Tested by scaling from 0 to ~500 nodes as fast as possible (~90 seconds) a few times with a 30s broadcast timeout. Seems to resolve issue discussed in thread.
=> Expose BroadcastTimeout configuration parameter

serf/serf_test.go
=> Reworks reap handler test to be less flaky (and not panic if it fails).

client/const.go, client/rpc_client.go, cmd/serf/command/force_leave_test.go, cmd/serf/command/query.go, cmd/serf/command/query_test.go, serf/config.go, serf/config_test.go, serf/delegate.go, serf/event.go, serf/event_test.go, serf/messages.go, serf/messages_test.go, serf/query.go, serf/serf.go, serf/serf_test.go, website/source/docs/commands/query.html.markdown
Adds messageRelayType for sending query responses through multiple (defaults to 3 for now) randomly chosen nodes for robustness.
=> Relay query responses through a few randomly chosen nodes

serf/config.go, serf/serf.go
This is basically the exact same as the memberlist package.
=> Add support for directly specifying the logger instead of the log output

serf/snapshot.go
Unless I am unaware of some odd feature there is no need to set the execute bit on the file permissions of created snapshot files.
=> Remove the execute flag from the created snapshot files

vendor/github.com/hashicorp/go-sockaddr/LICENSE, vendor/github.com/hashicorp/go-sockaddr/Makefile, vendor/github.com/hashicorp/go-sockaddr/README.md, vendor/github.com/hashicorp/go-sockaddr/doc.go, vendor/github.com/hashicorp/go-sockaddr/ifaddr.go, vendor/github.com/hashicorp/go-sockaddr/ifaddrs.go, vendor/github.com/hashicorp/go-sockaddr/ifattr.go, vendor/github.com/hashicorp/go-sockaddr/ipaddr.go, vendor/github.com/hashicorp/go-sockaddr/ipaddrs.go, vendor/github.com/hashicorp/go-sockaddr/ipv4addr.go, vendor/github.com/hashicorp/go-sockaddr/ipv6addr.go, vendor/github.com/hashicorp/go-sockaddr/rfc.go, vendor/github.com/hashicorp/go-sockaddr/route_info.go, vendor/github.com/hashicorp/go-sockaddr/route_info_bsd.go, vendor/github.com/hashicorp/go-sockaddr/route_info_default.go, vendor/github.com/hashicorp/go-sockaddr/route_info_linux.go, vendor/github.com/hashicorp/go-sockaddr/route_info_solaris.go, vendor/github.com/hashicorp/go-sockaddr/route_info_windows.go, vendor/github.com/hashicorp/go-sockaddr/sockaddr.go, vendor/github.com/hashicorp/go-sockaddr/sockaddrs.go, vendor/github.com/hashicorp/go-sockaddr/unixsock.go, vendor/github.com/hashicorp/memberlist/config.go, vendor/github.com/hashicorp/memberlist/memberlist.go, vendor/github.com/hashicorp/memberlist/net.go, vendor/github.com/hashicorp/memberlist/state.go, vendor/github.com/hashicorp/memberlist/util.go, vendor/github.com/sean-/seed/LICENSE, vendor/github.com/sean-/seed/README.md, vendor/github.com/sean-/seed/init.go, vendor/vendor.json
This gets a number of improvements:
* Gossip will continue to flow to dead nodes for a short while to better help them refute if they are working again or were falsely accused.
* Uses the go-sockaddr library to look for private IP addresses, which prefers non-loopback private addresses over loopback ones.
* Properly seeds Go's random number generator using the seed library.
=> Updates memberlist (and adds some new required dependencies).

serf/serf.go
Fixes https://github.com/hashicorp/serf/issues/426 by using `serf.NumNodes` in place of the `len(serf.members)` calls in the instantiation of TransmitLimitedQueue.
=> Fix race condition in NumNodes for TransmitLimitedQueue

serf/serf.go
A net.IP may be represented by both by a 4 as well as a 16 byte long byte slice. Because of this, it is not safe to compare IP addresses using bytes.Equal as the same IP address using a different internal representation will produce mismatches.
*Note, this PR was not initiated by my use of this package and noticing a bug, rather by creating an extension proposal for `go vet` and that signalling the possible misuse in this library.*
Cheers :)
=> Fix possible IP comparison error

serf/query.go, serf/serf.go
There were two races in the QueryResponse type:
1. In the Finished method the read on r.closed needs to be protected
2. When sending the response on the channel a check needs to be made if the channel has been closed while holding the lock.
Both of these races have been fixed with this PR.
=> Fix a few races around the QueryResponse

serf/serf.go
This patch simplifies the logger setup code giving preference to a
custom logger, falling back to a standard logger with the given log sink
or stderr if no sink was provided.
=> log: allow specifiying logger and logOutput

cmd/serf/command/agent/config.go, serf/config.go, serf/internal_query.go, website/source/docs/agent/options.html.markdown
=> Add a config option to disable writing keyring to a file

serf/snapshot.go
This attempts a compaction every 30 seconds after an error when appending to the snapshot file (both local and remote). After this is merged we should be able to gracefully recover from disk availability or other intermittent write errors without needing a restart.
This fixes #477
=> Snapshot write fail recover

serf/delegate.go, serf/serf.go
eventJoinIgnore is read and written in two different places
but access is not synchronized. Using the joinLock on read
blocks progress.
=> Fix data race on eventJoinIgnore

serf/serf.go
If the Serf agent is configured with coordinates disabled (i.e. `serf.Config.DisabledCoordinates = true`), invoking `Serf.Stats()` causes a segmentation fault. That's because, in order to set the value of `"coordinate_resets"` in the stats map, `Serf.Stats()` invokes `s.coordClient.Stats()`, with `s.coordClient `being a nil pointer.
This pull request fixes this issue by setting the value of `"coordinate_resets"` in the stats map only if coordinates are enabled.
=> Fix Serf.Stats() panic when coordinates are disabled

cmd/serf/command/agent/ipc.go
On Windows, Serf outputs a WSARecv error message every time when it
receives a client IPC request.
Its code seems to try to suppress such an error message but it just
matches "WSARecv" word against an error message though the actual one
only has a lower case "wsarecv" word in recent Go implementation.
This fixes it by comparing a lower cased error message with "wsarecv",
in other words, doing case-insensitive match.
---
Here is the actual error message example
```
2017/07/10 18:46:00 [ERR] agent.ipc: failed to decode request header: read tcp 127.0.0.1:7373->127.0.0.1:50390: wsarecv: An existing connection was forcibly closed by the remote host.
```
and "wsarecv" lower cased word seems to come from ﻿https://github.com/golang/go/commit/055ecb7be5805e07498488c59c6f01644fdacccc#diff-035f045315 …
=> Suppress WSARecv error by case-insensitive match

coordinate/client.go, coordinate/client_test.go
I could reliably reproduce both extreme negative adjustment values and negative rtt estimates by feeding it time.maxvalue as the rtt value, which is a valid return values from the `time.Sub` method. 
This patch makes it so that we reject any updates that contain rtt durations that are not in a range from 1 to 32400 seconds (9 hours). Another option is to force updates > 9 hrs to be = 9hrs, but rejecting it seemed better to avoid corrupted data feeding into the algorithm.
The 32000 was something I found from some experimentation with Vivaldi starting with two sets of coordinates at the origin and trying to get them to drift to the point where adjustment becomes this large negative value. 9 hours also seems like a conservative but large enough upper bound on the previously unbounded rtt …
=> Protect against ping periods that are out of range

website/source/intro/getting-started/install.html.markdown
```
$ brew search serf
==> Searching local taps...
serf
==> Searching taps on GitHub...
==> Searching blacklisted, migrated and deleted formulae...
If you meant "serf" specifically:
It was migrated from caskroom/cask to homebrew/core.
```
=> Homebrew no longer uses cask to install serf

coordinate/client.go, serf/ping_delegate.go
These aren't harmful to the Vivaldi algorithm since we have a min 1 us RTT we use when this happens, so it's not worth logging them. We added a counter so we can still observe these, since we don't have a great root cause story on why we see them, other than a guess that some systems have a low monotonic clock granularity.
We also added a new metric for rejected coordinates and moved the detailed message to the TRACE level.
This is a fix for https://github.com/hashicorp/consul/issues/3789.
=> Prevents log spam from zero RTTs.

serf/serf.go
Stats function can cause deadlock by holding on to the readLock on memberLock while attempting to read the length of broadcast queues. This is described in this [issue](https://github.com/hashicorp/consul/issues/4011).
This fix releases the memberLock before invoking the broadcast queues.
This is the stacktrace of the 2 goroutines that are stuck in the deadlock
GoRoutine 1 (waiting for memberlock.RLock in serf.go)
--------------------------------------------------------
0  0x000000000042d6ec in runtime.gopark
at /goroot/src/runtime/proc.go:288
1  0x000000000042d7de in runtime.goparkunlock
at /goroot/src/runtime/proc.go:293
2  0x000000000043ed74 in runtime.semacquire1
at /goroot/src/runtime/sema.go:144
3  0x000000000043e999 in sync.runtime_Semacquire
at /goroot/src/runtime/sema.go:56
4 …
=> Fix for deadlock between stats() in serf and getBroadcasts() in memberlist

cmd/serf/command/agent/command_test.go, serf/config.go, serf/delegate.go, serf/delegate_test.go, serf/serf.go, serf/serf_test.go
This PR adds a configurable leave timeout to allow leave intent broadcasts to propagate before returning from the Leave method. 
It also fixes an edge case in  anti entropy sync where a left member in the push/pull message's payload would not get processed because its lamport time was incorrectly set.
Brings in work done in an experimental branch by @slackpad
=> Ensure node leave intents are handled correctly

.travis.yml
This commit updates Travis CI to use Go 1.10.x - i.e. the latest version at a given point in the 1.10 series.
=> build: Update to Go 1.10.x

serf/snapshot.go
This PR replaces a static maximum snapshot size with a relative size based on the number of nodes. This is to avoid frequent compaction for large clusters.
Depends on #524
=> Snapshot compaction threshold is relative to node count

cmd/serf/command/agent/agent.go, cmd/serf/command/agent/command.go, cmd/serf/command/agent/config.go, cmd/serf/command/agent/config_test.go, website/source/docs/agent/options.html.markdown
Adds CLI argument `enable-compression=<bool>` to `serf agent`.
This is to make debugging much easier w/o having LZW compression of messages by `memberlist`.
Signed-off-by: Anton Antonov <anton.synd.antonov@gmail.com>
@banks
=> Make event compression optional

serf/event.go, serf/internal_query.go, serf/internal_query_test.go, serf/keymanager.go, website/source/docs/commands/keys.html.markdown
This truncates the list key response in case it contains too many keys so that the message would be bigger than allowed and serf wouldn't been able to send it out.
This is what it looks like if you run into it: 
```
2019/01/15 12:51:33 [INFO] serf: Received list-keys query
2019/01/15 12:51:33 [ERR] serf: Failed to respond to key query: response exceeds limit of 1024 bytes
```
If there are too many keys in a response, the keys will be removed from the end until it fits. That way the primary key (index 0) is always part of the response. In case of truncation there will be a warning, stating that it has been truncated. 
The receiving agent checks if the message is close to the limit and emit a warning about truncation as well.
I have to admit that this approach feels a little strange, but I …
=> Truncate key list response

cmd/serf/command/agent/command.go, cmd/serf/command/agent/config.go, serf/config.go, serf/serf.go, serf/serf_test.go, website/source/docs/agent/basics.html.markdown, website/source/docs/internals/gossip.html.markdown
Different usages, needs different `UserEventSizeLimit`.
It's understood that having a big event size is going to make the
broadcast and replication across the cluster slow depending on the size.
Other serf broadcast timeout and replication timeout settings must be configured accordingly!
Also fix the check:
* Make it more reliable in terms of payload size since only the encoded message is checked.
* Make it consistent with `QuerySizeLimit`.
@banks Another one. Although I require some HashiCorp knowledge why it wasn't configurable before. My idea is to piggyback on the `UserEvent` to send application events that may be greater than `512` bytes, but in any case they must be configurable. `QuerySizeLimit` has been taken into account as another example how it is risky, yet configurable.
P.S …
=>  Make `UserEventSizeLimit` configurable and fix `UserEventSizeLimit` check

cmd/serf/command/agent/agent_test.go, cmd/serf/command/agent/command.go, cmd/serf/command/agent/config.go, cmd/serf/command/agent/rpc_client_test.go, cmd/serf/command/keygen.go, cmd/serf/command/keygen_test.go, cmd/serf/command/keys_test.go, serf/internal_query_test.go, serf/keymanager_test.go, serf/serf_test.go, website/source/docs/agent/encryption.html.markdown, website/source/docs/agent/options.html.markdown, website/source/docs/agent/rpc.html.markdown, website/source/docs/internals/security.html.markdown
This PR improves the security of the gossip protocol by increasing the size of the default encryption key used.
=> Bump encryption key size from 16 to 32 bytes

README.md
When I compile serf with go1.9 there are many error:# github.com/hashicorp/serf/vendor/github.com/miekg/dns
vendor/github.com/miekg/dns/dnssec_keyscan.go:295:7: undefined: strings.Builder
vendor/github.com/miekg/dns/msg_helpers.go:270:8: undefined: strings.Builder
vendor/github.com/miekg/dns/serve_mux.go:43:9: undefined: strings.Builder
vendor/github.com/miekg/dns/types.go:422:10: undefined: strings.Builder
....
while strings.Builder was added in go1.10 :)
=> Correct README about go version

client/const.go, client/rpc_client.go, cmd/serf/command/agent/agent.go, cmd/serf/command/agent/ipc.go, cmd/serf/command/agent/rpc_client_test.go, cmd/serf/command/force_leave.go, cmd/serf/command/force_leave_test.go, serf/messages.go, serf/serf.go, serf/serf_test.go, website/source/docs/commands/force-leave.html.markdown
Adds the `-prune` flag to the `forceleave` command to allow for an agent to be completely removed from Serf's list of members. This can only be ran with the force leave command, so this can only be ran on nodes in a failed or left state.
=> Trigger Removal for Left/Failed Agents

serf/serf.go, serf/serf_test.go, testutil/retry/retry.go, testutil/retry/retry_test.go
ForceLeave previously didn't take into consideration what occurs during `StatusLeaving` and `StatusAlive`. The `handlePrune()` function was created to allow for different statuses to prune nodes.
=> Update ForceLeave Prune

go.mod, go.sum, serf/merge_delegate.go
needs: https://github.com/hashicorp/memberlist/pull/223. This is part of something bigger too!
=> Set status to left if memberlist did it

go.mod, go.sum
Originally tried indirect pinning to an older version but it looks like transitive deps resolved to something slightly newer but still before the regression was introduced in https://github.com/golang/sys/commit/5766fd39f98ddd8d769ad4aedcee557dd28de90f#diff-2b37904226feaa1ac0c049523015d0bcL126-R128
=> fix: remove indirect golang.org/x/sys pin to avoid FreeBSD regression

serf/config.go, serf/delegate.go, serf/serf.go, serf/serf_test.go
Fixes this scenario:
When two leave events for the same node (with different ltimes) are
received by two or more additional nodes without any intermediate state
transitions it will lead to them setting up an infinite gossip echo
chamber rebroadcasting the original node's leave.
When in this situation the only way to recover would be to either:
- Bring the node back so it can send out a fresh "alive" message.
- Use force-leave prune to purge the node's existence from the cluster.
There are two known ways to arrive in this situation:
1. Have a node leave the cluster and then from a differnet node initiate
a force-leave. This is the easiest way to reproduce.
2. Have a node leave, rejoin, and leave again in quick succession. This
requires winning a lot of races in just the right way to have …
=> Avoid issue where two unique leave events for the same node could lead to infinite rebroadcast storms

go.mod, serf/config.go, serf/delegate.go, serf/serf.go, serf/serf_test.go
Backport of #606 to follow serf v0.8.5
=> [backport on v0.8.5] Avoid issue where two unique leave events for the same node could lead to infinite rebroadcast storms

serf/internal_query.go, serf/internal_query_test.go, serf/keymanager.go, serf/keymanager_test.go
This PR modifies the key list response and adds a field for the primary key of a node. They will be accumulated similarly to the other keys.
=> add primary key to keylist response

coordinate/performance_test.go, coordinate/phantom.go, coordinate/util_test.go, serf/config.go, serf/merge_delegate.go, serf/merge_delegate_test.go, serf/serf.go, serf/serf_test.go
There are actually 3 commits in this PR:
* The first commit is to make the golangci linter happy with simplifying some range expressions.
* The second commit fixes an issue recently introduced that would cause all messages to be rejected for invalid reasons.
* The third commit is the real work of this PR which allows an application using serf to override the reconnect timeout on a per-node basis. There is an interface they can optionally provide and serf will use its only method to request the per-node timeout. If no interface is provided then the normal reconnect timeout is used.
TODOS:
=> Add the ability for per-node reconnect timeouts to be specified by a Serf user

.circleci/config.yml, scripts/build.sh, serf/event_test.go, serf/serf_test.go
Also remove module cache, because downloading from the module proxy is faster than using the cache.
=> ci: use latest Go version and fix a flaky test

GNUmakefile
Currently `make dist` fails because it can't find file `cmd/serf/version.go`:
```
$ make dist
awk: can't open file cmd/serf/version.go
source line number 1
Please specify a version.
make: *** [dist] Error 1
```
=> Fix getting VERSION from version.go in makefile

serf/event.go
Users of the `serf` library may need to perform actions out of serf regarding the node initiating a query, therefore being able to access this information will be useful.
=> Add source node getter

serf/coalesce_member_test.go, serf/serf.go
=> finish the leave process if broadcasting leave timeout

.github/workflows/check.yml, .golangci.yml, cmd/serf/command/agent/invoke.go, cmd/serf/command/agent/ipc.go
prohibit serf from including code using the un-labeled go-metrics functions and methods.
=> golang-lint metrics label

coordinate/phantom.go
Count is zero, when `len(clients) <= 1`
=> Fix division by zero

serf/serf_test.go
This test was causing seemingly unrelated failures in other tests due to not releasing the ip address listener correctly.
=> Fix broken CICD tests

cmd/serf/command/agent/command.go, cmd/serf/command/agent/config.go, cmd/serf/command/agent/mdns.go, go.mod, go.sum
This PR:
* Allows specifying `iface` for mDNS: In our use case, we disable multicast on the interface that Serf binds to. However, we have another network where Serf can discover neighbors using multicast.
* Updates mDNS to v1.0.5: mDNS v1.0.5 enables the disabling of one of the IP stacks.
* Allows disabling one of the IP stacks in the config file and CLI arguments.
=> Enhance mDNS Functionality

go.mod, go.sum
**Bumped the following deps to remediate CVEs.**
- golang.org/x/net
- golang.org/x/crypto
=> Deps Bump for CVE fixes
