ops-misc/io.serfdom.serf.plist

Adds a launchd plist for use on Mac OS X

Add io.serfdom.serf.plist for launchd

---

testutil/addr.go

fixed overflow handling reported on https://github.com/hashicorp/serf/issues/295

https://github.com/hashicorp/serf/issues/295

---

command/agent/command.go
command/agent/config.go
command/agent/config_test.go
serf/config.go
serf/event.go
serf/serf.go
serf/serf_test.go
website/source/docs/agent/options.html.markdown

This adds a few more tests and some documentation updates on top of #342.

make query and query reponse configurable

---

scripts/setup_test_subnet.sh

Seems like there's a deeper issue, possibly related to IPv6. Reverting some of my thrashing (I do think keeping the ping first is a good idea).

Reverts Travis thrashing.

---

Godeps/Godeps.json
vendor/github.com/hashicorp/memberlist/.gitignore
vendor/github.com/hashicorp/memberlist/memberlist.go
vendor/github.com/hashicorp/memberlist/state.go
vendor/github.com/hashicorp/memberlist/util.go

Pulls in latest memberlist to git fix in https://github.com/hashicorp/memberlist/pull/71.

Updates memberlist.

---

website/source/docs/upgrading.html.markdown

Fix document.
https://github.com/hashicorp/serf/commit/ff9e8d5be84f8808449d77085d3263ae4381ad19

Fix missing closing backquote on document

---

GNUmakefile
serf/config.go
serf/serf.go

I originally planned on implementing this in memberlist but realized that doesn't keep state for failed nodes, so moving this up one level to Serf where it's a simple addition.

Adds a basic flap telemetry metric.

---

website/source/intro/getting-started/event-handlers.html.markdown

I assume this wasn't updated when new event types were added in the past.
Thanks

Correct number of Serf events in docs

---

website/source/docs/commands/agent.html.markdown

Added a direct link to the options to expedite lookup 😃

Add link to Serf options.

---

vendor/github.com/hashicorp/memberlist/config.go
vendor/github.com/hashicorp/memberlist/keyring.go
vendor/github.com/hashicorp/memberlist/memberlist.go
vendor/github.com/hashicorp/memberlist/net.go
vendor/github.com/hashicorp/memberlist/state.go
vendor/github.com/hashicorp/memberlist/util.go
vendor/vendor.json

To pull in the udp checksum stuff from [here](https://github.com/hashicorp/memberlist/pull/95).

Update memberlist vendor deps

---

vendor/github.com/hashicorp/memberlist/config.go
vendor/github.com/hashicorp/memberlist/state.go
vendor/github.com/hashicorp/memberlist/util.go
vendor/vendor.json

* There's now a short window where gossip will still flow to dead nodes so that they can more quickly refute.
* Improved suspicion timeout calculation.

Updates memberlist to pick up improvements.

---

serf/keymanager.go

We need to be able to set this from Consul.

Add relayFactor param to keyring functions

---

cmd/serf/command/agent/ipc.go
serf/event.go
serf/event_test.go
serf/query.go
serf/query_test.go
serf/serf.go
serf/serf_test.go

This fixes a couple loose ends from #439.

Plumbs relay factor through IPC layer and adds ACK relays.

---

serf/serf.go

I ran into this race today and here is a fix. #426

Fix race on getting length of serf.members

---

serf/serf.go

Closes the shutdown channel after memberlist is shutdown.

---

coordinate/client.go
coordinate/client_test.go
coordinate/coordinate.go
coordinate/coordinate_test.go
serf/ping_delegate.go
serf/serf.go
serf/snapshot.go
serf/snapshot_test.go

This is the Serf side of fixing https://github.com/hashicorp/consul/issues/3023.

Adds defensive checks for NaN and Inf values in network coordinates.

---

website/Gemfile
website/Gemfile.lock
website/Makefile
website/packer.json
website/redirects.txt
website/scripts/deploy.sh
website/source/community.html.erb

Remove people from community section This is going to be replaced with dynamic content from our CMS in the future, but we agreed to remove it in the interim. 
This also updates the deploy process and brings project-side redirects (if you did not have them already).

Remove people from community section

---

serf/config.go
serf/serf.go
serf/serf_test.go

See https://github.com/hashicorp/consul/issues/3705 for more details.

Adds additional controls for intent queue management.

---

website/source/docs/internals/gossip.html.markdown

This fixes https://github.com/hashicorp/serf/issues/502

Fix broken link to SWIM paper

---

website/source/docs/agent/options.html.markdown

docs: Improve clarity of -join documentation

---

vendor/github.com/hashicorp/go-sockaddr/GNUmakefile
vendor/github.com/hashicorp/go-sockaddr/README.md
vendor/github.com/hashicorp/go-sockaddr/ifaddr.go
vendor/github.com/hashicorp/go-sockaddr/ifaddrs.go
vendor/github.com/hashicorp/go-sockaddr/ipv4addr.go
vendor/github.com/hashicorp/go-sockaddr/rfc.go
vendor/github.com/hashicorp/go-sockaddr/route_info_linux.go
vendor/github.com/hashicorp/go-sockaddr/sockaddr.go
vendor/vendor.json

deps: Update github.com/hashicorp/go-sockaddr

---

serf/broadcast.go

This is the serf side of https://github.com/hashicorp/memberlist/pull/167/

ensure performance improvements in memberlist are activated

---

website/source/docs/internals/gossip.html.markdown

Signed-off-by: Stefan Wessels Beljaars <swesselsbeljaars@schubergphilis.com>

Fixed broken link to SWIM paper

---

.circleci/config.yml

Took me few hours to realize about this. Hope everyone finds this useful.

Update rpc Tag return value in doc

---

cmd/serf/command/agent/agent.go
cmd/serf/command/agent/command.go

This comment/log is for function "Start" which is refactored

fix some comment/log while starting agent

---

serf/serf.go
serf/serf_test.go

post-merge PR feedback from: https://github.com/hashicorp/serf/pull/606

various trivial fixes following #606

---

serf/merge_delegate.go

This just fixes a couple typos I randomly came across.

Fix typos in validateMemberInfo()

---

website/source/assets/javascripts/_simulator.js

fix _simulator.js number of nodes alert

---

serf/query.go
serf/serf.go

This is to fix the data race documented in https://github.com/hashicorp/serf/issues/650

fix a data race related to `query.ackCh`

---

coordinate/client.go
coordinate/config.go
go.mod
go.sum
serf/config.go
serf/delegate.go
serf/ping_delegate.go
serf/serf.go
serf/snapshot.go

Manual cherry pick the changes from [metrics-label-backport](https://github.com/hashicorp/serf/tree/metrics-labels-backport)
- adding metric labels to all metrics
- pass the metrics label down to memberlist

Add metrics labels

---

README.md

Add note to the top of the README to explain what happened to serf.io
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1208469636144498

Update README to explain where the website went

---

docs/index.html.markdown

This helps to provide some context for folks who are re-directed to that page about what happened to the website they thought they were going to
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1208469636144506

Copy README note about serf.io shutdown to docs landing page

---

.github/workflows/check.yml

- I have added unit test coverage in the checks.yml workflow
- The unit test coverage change was done to help understand the defects early in lifecycle and come up with a good solution for it.

Coverage test
